---
enabled: true
pack: iotdemopack
name: WH_IoT_Demo_destroy

type:
  ref: standard
  parameters:

trigger:
  type: core.st2.webhook
  parameters:
    url: lambda-iot-webhook

criteria:
  trigger.body.type:
    type: "equals"
    pattern: "DOUBLE"
action:
  ref: iotdemopack.IoT_Demo_destroy
  parameters:
    context:
      name: "{{trigger.body.name}}"
      type: "{{trigger.body.type}}"

